name: ml
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=3_kmp_llvm
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.6.1=h59595ed_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.4.26=py310h06a4308_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py310h89163eb_0
  - freetype=2.13.3=ha770c72_1
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h5888daf_0
  - greenlet=3.2.3=py310hf71b8c6_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - harfbuzz=11.0.0=h76408a6_0
  - icu=75.1=he02047a_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=16_linux64_mkl
  - libboost=1.86.0=h6c02f8c_3
  - libboost-python=1.86.0=py310ha2bacc8_3
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp20.1=20.1.7=default_h1df26ce_0
  - libclang13=20.1.7=default_he06ed0a_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.49=h943b412_0
  - libpq=17.5=h27ae623_0
  - librdkit=2025.03.3=h84b0b3c_0
  - libsqlite=3.50.1=hee588c1_4
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hf01ce69_5
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.5.0=hae8dbeb_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2022.1.0=hc2b9512_224
  - mkl-devel=2022.1.0=h66538d2_224
  - mkl-include=2022.1.0=h06a4308_224
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.5=h2d0b736_3
  - nettle=3.9.1=h7ab15ed_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openblas=0.3.30=pthreads_h6ec200e_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.0=h7b32b05_1
  - p11-kit=0.24.1=hc5aa10d_0
  - pandas=2.3.0=py310h5eaa309_0
  - pcre2=10.44=hc749103_2
  - pillow=11.2.1=py310h7e6dc6c_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycairo=1.28.0=py310h516fd05_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py310hfd10a26_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=7_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_0
  - rdkit=2025.03.3=py310hcd13295_0
  - readline=8.2=h5eee18b_0
  - reportlab=4.4.1=py310ha75aee5_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.7.0=py310h27f47ee_1
  - six=1.17.0=pyhd8ed1ab_0
  - sqlalchemy=2.0.41=py310ha75aee5_0
  - sqlite=3.50.1=h9eae976_4
  - svt-av1=1.4.1=hcb278e6_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchaudio=2.5.1=py310_cu121
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu121
  - tornado=6.5.1=py310ha75aee5_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.0
      - addict==2.4.0
      - aiobotocore==2.23.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - alabaster==0.7.16
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - botocore==1.38.27
      - cachetools==5.5.2
      - captum==0.2.0
      - cffi==1.17.1
      - cilog==1.3.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coverage==7.9.1
      - cramjam==2.10.0
      - crcmod==1.7
      - cryptography==45.0.4
      - cvxopt==1.3.2
      - datamol==0.12.5
      - decorator==5.2.1
      - dive-into-graphs==1.1.0
      - docutils==0.17.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - execnet==2.1.1
      - executing==2.2.0
      - fastparquet==2024.11.0
      - filelock==3.14.0
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gcsfs==2025.5.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.1.1
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - graphium==2.4.7
      - grpcio==1.73.1
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.2
      - hydra-core==1.3.2
      - imagesize==1.4.1
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipython==8.37.0
      - jedi==0.19.2
      - jmespath==0.10.0
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - littleutils==0.2.4
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - loguru==0.7.3
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - matplotlib==3.5.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - minimol==1.3.5
      - ml-collections==1.1.0
      - mmcv==2.2.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - multidict==6.5.0
      - munch==2.5.0
      - mup==1.0.0
      - mypy-extensions==1.1.0
      - networkx==2.8
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-ml-py==12.575.51
      - oauthlib==3.3.1
      - ogb==1.3.6
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - outdated==0.2.2
      - packaging==24.2
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==3.20.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py==1.11.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pynvml==12.0.0
      - pyscf==2.9.0
      - pytest==7.1.2
      - pytest-cov==3.0.0
      - pytest-forked==1.6.0
      - pytest-xdist==2.5.0
      - pytorch-lightning==2.5.2
      - pytz==2023.4
      - rdkit-pypi==2022.9.3
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - rsa==4.9.1
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.12
      - s3fs==2025.5.1
      - scikit-learn-extra==0.3.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - selfies==2.2.0
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - setuptools==60.2.0
      - shap==0.48.0
      - shellingham==1.5.4
      - slicer==0.0.8
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.7
      - sphinx==5.3.0
      - sphinx-rtd-theme==1.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torchmetrics==0.10.3
      - tqdm==4.65.2
      - traitlets==5.14.3
      - typed-argument-parser==1.7.2
      - typer==0.16.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - unicore==0.0.1
      - urllib3==1.26.20
      - wandb==0.20.1
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yapf==0.43.0
      - yarl==1.20.1
prefix: /u/lhe11/anaconda3/envs/ml
